replicaCount: 1

image:
  repository: nagarjunapavuluri/gitops-app
  tag: latest
  pullPolicy: Always 

service:
  type: NodePort
  port: 5000
  targetPort: 5000

livenessProbe:
  httpGet:
    path: /health
    port: 5000       
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000       
  initialDelaySeconds: 10
  periodSeconds: 10
resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50