apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-app.fullname" . }}
  labels:
    {{- include "gitops-app.labels" . | nindent 4 }}

spec:
  type: NodePort

  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30008

  selector:
    app: gitops-app
    version: {{ .Values.version }}